### ISSUE TITLE
Confusions about the decay parameter λ

### ISSUE THREAD

**Issue by Leopold2333** [OpenNLPLab/TransnormerLLM#12]
In the paper, λ is described as $\lambda^{s-t}$ and aims to weaken the interaction of remote tokens at a lower level. However, I'm confused that if s<t, the interaction may be strenthened. Should it be $\lambda^{|s-t|}$ so that the TRF could be set right?

**Comment by Doraemonzzz** [comment]
Yes, you are correct. Simply put, the similarity should be computed using the following formula (non-causal):  

$$  
e_{st} = q_s k_t^\top \lambda^{|s-t|},  
o_s = \sum_{t} e_{st} v_t.
$$  

Note that in the paper, since we are discussing language models (causal), we have \( t \leq s \). Therefore, the absolute value is not needed.  

To compute the above formula, you might need to use the lightning attention function as follows:  

```python  
o1 = lightning_attn_func(q, k, v, s)  
o2 = lightning_attn_func(torch.flip(q, dims=[-2]), torch.flip(k, dims=[-2]), torch.flip(v, dims=[-2]), s)  
o = o1 + o2  
```  

It is worth noting that the diagonal part is added twice. Using this method, the diagonal elements are computed twice, resulting in the output:  

```math
\bar{o}_s = o_s + \sum_{t} q_t k_t^\top v_t. 
```

**Comment by Leopold2333** [comment]
Get it. Thank you!
